### ISSUE TITLE
Additional props

### ISSUE THREAD

**Issue by randikaprasad1418** [creativetimofficial/react-bootstrap-wizard#1]
How to pass additional props to share data between tabs?

**Comment by EINazare** [comment]
Hello @crowderia ,

And thank you for your interest in using our products.
We haven't implemented this behavior in our product, but now that you've opened this issue, it seems to me that this would be something that people would need in their flow.
I see how i will have time, and will try to add this functionality/behavior, and maybe make a better documentation with live demo etc.

Best,
Manu

**Comment by renanbirlem** [comment]
@crowderia You can pass on component, like this:

`<ReactWizard
                            steps={[
                                {
                                    stepName: 'Step Name',
                                    component: <StepComponent
                                        props={this.state.props}
                                    />
                                 }
                            ]}
                            navSteps
                            validate
                            finishButtonClick={this.handleFinishButton}
                            title="Title"
                            subtitle="Subtitle"
                            headerTextCenter
                            color="primary"
                        />`

**Comment by cherma** [comment]
While adding props to component,
<StepComponent props={this.state.props}  />

validate doesnt seem to work.

**Comment by EINazare** [comment]
Hello @cherma ,

Yes, that i think would not work because we add a innerRef in the steps of the wizard (and that innerRef has to be on the component itself), by passing it like @renanbirlem has, than i believe that the innerRef doesn't render where it should be.

Best,
Manu

**Comment by cherma** [comment]
@EINazare  
I need to take values to the final step from the previous steps and validate to work in every step.
kindly let us know on priority.

we tried 2 methods

1)In one we cannot pass additional props to get 2 way binding done 
to bring values to parent component

2) if we pass component as such in steps our is validate is not working.


we need solution as to get values at final step and validate working together.

we bought now ui template , so please help us on priority

**Comment by EINazare** [comment]
Hello again @cherma ,

This week is dedicated only for Material React products, as i can see, i am doing a bit well on those and i think i am going to finish my work on those quite soon and maybe i am going to be able to make some changes on this product as well, but  i cannot promise anything. I am doing my best.

Best,
Manu

**Comment by DarioI** [comment]
Hi,

We have a problem where the isValidated function is not being called anymore. Has this something to do with the fact that I pass callbacks and data to the steps as follows:

``var steps = [
        { stepName: "Create", component: <Step1 handleLabels={this.handleLabels} handleName={this.handleName} algo={this.props.location.state.algorithm} />},
        { stepName: "Upload", component: <Step2 labels = {this.state.labels} />},
        { stepName: "Train", component: Step3 }
    ];
``
The wizard is quite useless if we can't pass data nor callbacks? Any update here?

**Comment by EINazare** [comment]
Hello @DarioI ,

Thank you for your interest in using our product and sorry for this late response (i've been on a small vacation - next week i also be on vacation).
If you'll check the CHANGELOG from this product you'll see that the last update was done on 2018-02-09, and this issue is from April (04) - this means that there is no update here. Unfortunately we are full of work on our other products. This was just a component made by us to help with our other products, but since it is open source you can create a pull request with this issue solved, if not then when i'll have time i'll make some necessary changes.

Best,
Manu

**Comment by EINazare** [comment]
Hello guys,

Please read the changelog: https://github.com/creativetimofficial/react-bootstrap-wizard/blob/master/CHANGELOG.md
Now the props are being passed to the steps through the stepProps prop.

Best,
Manu

**Comment by smithmr** [comment]
> Hello guys,
> 
> Please read the changelog: https://github.com/creativetimofficial/react-bootstrap-wizard/blob/master/CHANGELOG.md
> Now the props are being passed to the steps through the stepProps prop.
> 
> Best,
> Manu

The StepProps do not update correctly.

Once they are passed in if the parent's state updates the props are not updated.

```steps = [
    {
      stepName: "Create",
      stepIcon: "tim-icons icon-cart",
      component: Step1,
      stepProps: {
        bankAccounts: this.props.bankAccounts
      }
    },```

```bankAccounts: [],```

Once Bank accounts are populated the Step1 props do not get updated.

**Comment by barrychapman** [comment]
this is insane. does anything work?

**Comment by barrychapman** [comment]
> Hello guys,
> 
> Please read the changelog: https://github.com/creativetimofficial/react-bootstrap-wizard/blob/master/CHANGELOG.md
> Now the props are being passed to the steps through the stepProps prop.
> 
> Best,
> Manu

Will this ever be fixed?
