### ISSUE TITLE
How can i add onClick for finsh button?

### ISSUE THREAD

**Issue by jamalabo1** [creativetimofficial/react-bootstrap-wizard#12]
Can i detect when user clicks on Finsh Button?

i have tried `finishButtonClick` and `onClick` but did't work

**Comment by Ignefolio** [comment]
Hello jamalabo1,

```
finishButtonClick={this.onWizardFinish}

onWizardFinish(){
}
```

This should work although, in the version 0.0.4, the finish button doesn't appear.
I have created a pull request, however, nothing happened since then.

**Comment by EINazare** [comment]
Hello again @Ignefolio ,

I am sorry, i haven't had time for this issue.
We've had a lot of work to do here at creative-tim.
I am sure that this week i'll have time to accept your PR and publish it on npmjs as well.

Best,
Manu

**Comment by EINazare** [comment]
Hello @jamalabo1 

Is this still an issue?

@Ignefolio i've updated this product.

Best,
Manu

**Comment by EINazare** [comment]
Hello again @jamalabo1 ,

Can you please show me your use case?

Best,
Manu
