### ISSUE TITLE
How to send props from wizard to steps???

### ISSUE THREAD

**Issue by chiragkini** [creativetimofficial/react-bootstrap-wizard#13]
Hi team,

I am trying to send props from wizard to steps which had component in it but not able to do it.

Lets say i have index.js
            <CustomerWizard {...this.props} onSubmit={this.addCustomer} selectProductData={this.props.selectProductData} doSearchProduct={this.searchProducts}  />

CustomerWizard.js
================
var steps = [
   { stepName: "Customer Details", component: CustomerDetail },
  { stepName: "Product Details", component: VehicleRegistrationDetails },
 
  { stepName: "Transaction Details", component: Transaction },
   { stepName: "Account Details", component: AccountDetail },
  { stepName: "Bank Details", component: BankDetails },
  
];
class CustomerWizard extends React.Component {
  constructor(props){
    console.log("Props in CustomerWizard ::",props)
    super(props)
  }

  finishButtonClick(allStates) {
    console.log(allStates);
  }
  render() {
    return (
      <Container fluid style={{ marginTop: "15px" }}>
        <Row>
          <Col xs={12} md={12} className="mr-auto ml-auto">
          <form onSubmit={this.props.handleSubmit} className="form-horizontal" >
            <ReactWizard
              {...this.props}
              steps={steps}
              navSteps
              title="Customer Registration"
              headerTextCenter
              validate
              color="#f86332"
              finishButtonClick={this.finishButtonClick}
            />
            </form>
          </Col>
        </Row>
      </Container>
    );
  }
}

export default reduxForm({
  form: 'customerForm',
  initialValues:{
      personalDetail:{},
      purchasedProducts:[{ qty:1}]
  }
})(CustomerWizard)

In this case how to i send all this  {...this.props} onSubmit={this.addCustomer} selectProductData={this.props.selectProductData} doSearchProduct={this.searchProducts}  to my steps ?????

in steps components props are missing there are not available.

**Comment by EINazare** [comment]
Hello there @chiragkini ,

And than you for your interest in using our products.
As of moment we have not implemented this functionality.
If you want, you can make a pull request (PR) and add this functionality.

Best,
Manu

**Comment by EINazare** [comment]
Hello there @chiragkini ,

We've added a new prop inside the steps prop.
Take a look at our Changelog and Readme.

Best,
Manu
