### ISSUE TITLE
 How to return to step 0??

### ISSUE THREAD

**Issue by ricardomultiversoft** [creativetimofficial/react-bootstrap-wizard#15]
How to return to step 0 after clicking on the finish button, without using previous button??

**Comment by EINazare** [comment]
Hello there @ricardomultiversoft ,

Thank you for your interest in working with this package.
You could press the nav-tabs if you do not want to use the previous button.

Best,
Manu

**Comment by giulianf** [comment]
Hi,
Do you have a props for this?
Thx
