### ISSUE TITLE
Step.component: can it be an instance of React.Component?

### ISSUE THREAD

**Issue by msantos-sw** [creativetimofficial/react-bootstrap-wizard#16]
In line 281 is explicit that step.component can it be an instance of React.Component. If this line is right the prop types needs to be updated to (line 371):

...
      component: PropTypes.oneOfType([
        PropTypes.func,
        PropTypes.instanceOf(React.Component)
      ]).isRequired
...

Tried to push a branch with this fixing but got forbidden.

**Comment by EINazare** [comment]
Hello there @msantos-sw ,

Thank you for your interest in working with this component.
Does the `PropTypes.func` not include `PropTypes.instanceOf(React.Component)`?
Isn't the `React.Component` actually a function?

Best,
Manu
