### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by jpmelnik** [creativetimofficial/react-bootstrap-wizard#19]
Can I Extend or Replace the Wizard Layout? How can I do that?

Thanks.

**Comment by EINazare** [comment]
Hello there @jpmelnik ,

Thank you for your interest in working with our products.
At the moment you can't change the Wizard Layout.
You can fork this repo and change its code how you may please.

Best,
Manu

**Comment by barrychapman** [comment]
> Hello there @jpmelnik ,
> 
> Thank you for your interest in working with our products.
> At the moment you can't change the Wizard Layout.
> You can fork this repo and change its code how you may please.
> 
> Best,
> Manu

@EINazare no we cannot because the src is all removed.

**Comment by EINazare** [comment]
> > Hello there @jpmelnik ,
> > Thank you for your interest in working with our products.
> > At the moment you can't change the Wizard Layout.
> > You can fork this repo and change its code how you may please.
> > Best,
> > Manu
> 
> @EINazare no we cannot because the src is all removed.

Hello again, @barrychapman ,

Actually, you can, since this is the whole project, it only comes with an index.js file, and that is it. Please take a look inside the index.js.

Best,
Manu
