### ISSUE TITLE
now-ui-dashboard-react css prevents finnish button from being displayed

### ISSUE THREAD

**Issue by aaronkitchens** [creativetimofficial/react-bootstrap-wizard#2]
When using this wizard in conjunction with the now-ui-dashboard-react it would appear that this style prevents the finish button from ever being displayed.

src/assets/scss/now-ui-dashboard/plugins/_plugin-card-wizard.scss

.btn-finish {
    display: none; }

**Comment by EINazare** [comment]
Hello @aaronkitchens ,

Thank you for your interest in using our products.
On our next update we are going to deleted that bit of css. Not sure why it would be there in the first place.

Best,
Manu
