### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by rayan-nativex** [creativetimofficial/react-bootstrap-wizard#21]
As I came across the documentation I wanted to send some properties to the child component..
I got mislead by the following:

```
var steps = [
  {
    stepName: "About",
    stepIcon: "tim-icons icon-single-02",
    component: Step1
  },
  {
    stepName: "Account",
    stepIcon: "tim-icons icon-settings-gear-63",
    component: Step2
  },
  {
    stepName: "Address",
    stepIcon: "tim-icons icon-delivery-fast",
    component: Step3,
    stepProp: {
      prop1: true,
      prop2: "A string"
    }
  }
];
```

Please replace **stepProp** by **stepProps**

**Comment by EINazare** [comment]
Hello there @rayan-nativex ,

Thank you for sharing this with us and sorry for the misleading.
These days I'll make an update to this project.

Best,
Manu

**Comment by spoecker** [comment]
Any plans on updating the plugin anytime soon?
