### ISSUE TITLE
How to add a custom button near next or finish button?

### ISSUE THREAD

**Issue by Vinaythegreat** [creativetimofficial/react-bootstrap-wizard#22]
Hi, 

I would like to add a save progress button as in the image. I feel like there is no direct option in the react version. Do the package support adding the custom button natively ?
![image](https://user-images.githubusercontent.com/5231532/56565493-25999000-65ce-11e9-9bbc-26059891931a.png)

**Comment by EINazare** [comment]
Hello there, @Vinaythegreat ,

Thank you for your interest in working with this plugin.
Unfortunately, you cannot add that button to our plugin.
The best way to make use of a save progress button would be to add it inside a step.

Best,
Manu
