### ISSUE TITLE
Update nextButtonClick() with Async!

### ISSUE THREAD

**Issue by peter-sorbo** [creativetimofficial/react-bootstrap-wizard#25]
I want to provide some clarification or help to people using the wizard with HTTP requests. Hopefully the docs could be updated to clarify how isValidated() works or how to use it with async.

DETAILS: I've been using the Wizard to validate a Login request. i.e. axios.post('/login') -> if username & password are ok -> next step, else -> throw validation error. What I didn't realize is that isValidated() is being called by nextButtonClick() which is synchronous, so it doesn't wait for the HTTP request to resolve before changing steps. Simply adding async to NextButtonClick() lets it wait for the request to resolve, and allows you to use HTTP requests with the wizard.

Hope this saves you some frustration!

NextButtonClick()

      async nextButtonClick() {
      if (
      (this.props.validate &&
        ((this.refs[this.props.steps[this.state.currentStep].stepName]
          .isValidated !== undefined &&
          await this.refs[
            this.props.steps[this.state.currentStep].stepName
          ].isValidated()) ||
          this.refs[this.props.steps[this.state.currentStep].stepName]
            .isValidated === undefined)) ||
      this.props.validate === undefined ||
      !this.props.validate
    )

isValidated()

    async isValidated() {
        let response = await axios.post('http://0.0.0.0:8080/accounts?action=submit', {
           username: this.state.username,
           password: this.state.password,
           api_type: this.props.wizardData['Select Device Type'].api_type
        })

    if (response.Status===200) {
    	return true
    } else {
    	return false
    }
  }

**Comment by spoecker** [comment]
Any plans on updating the plugin anytime soon?
