### ISSUE TITLE
remove buttons in last step

### ISSUE THREAD

**Issue by pooya-alen1990** [creativetimofficial/react-bootstrap-wizard#27]
Hi
Would you please inform me how can i remove buttons in last step ?

Best regards

**Comment by EINazare** [comment]
Hello there, @pooya-alen1990 ,

At the moment you cannot disable them.
I think we will not add this functionality into this project, since most of our users would prefer to have a previous and finish button.

Best,
Manu

**Comment by nj20** [comment]
Hey @EINazare 

I think disabling the finish button could be useful in cases where you are making a request to a service and you want to avoid the user from clicking the button twice. 

Do you have any suggestions on how this case can be handled with this wizard?

**Comment by EINazare** [comment]
Hello there, @nj20 ,

You can use the `finishButtonClick` for this.
When the user presses the finish button, you can send this function, which will change a state in your component (where the wizard is rendered), and with that state, you can then add a disabled class on the finish button through the `finishButtonClasses`.

Best,
Manu

**Comment by nj20** [comment]
Hey @EINazare,

Thanks for the suggestion.
