### ISSUE TITLE
Can't resolve 'react-bootstrap-wizard/dist/react-wizard.css'

### ISSUE THREAD

**Issue by amolksagar** [creativetimofficial/react-bootstrap-wizard#32]
Hi, 

I am trying to use the latest version of react-bootstrap-wizard component. I have reffered the readme and have installed the latest version 0.0.8 

However, when I try to do a npm  start, I get the below mentioned error:
**Module not found: Can't resolve 'react-bootstrap-wizard/dist/react-wizard.css'**

I have added the below import to my project as per the readme instructions of this project at https://github.com/creativetimofficial/react-bootstrap-wizard/blob/master/README.md

import "react-bootstrap-wizard/dist/react-wizard.css"

I opened the react-bootstrap-wizard folder under node_modules and it actually does not have the react-wizard.css file for version 0.0.8

For 0.0.7 it does have that file and everything works fine.Kindly help. The issue is quiet evident if you simply follow the readme of this github project

**Comment by EINazare** [comment]
Hello there, @amolksagar ,

Sorry for this issue.
I will update this package today and solve this issue.

Best,
Manu
