### ISSUE TITLE
You cant add class names to finish button

### ISSUE THREAD

**Issue by cherma** [creativetimofficial/react-bootstrap-wizard#4]
{this.state.finishButton ? (<Button className={"btn-finish" + (**this.finishButtonClasses** !== undefined ? (" "+this.props.finishButtonClasses):"")} onClick={() => this.finishButtonClick()}>{this.props.finishButtonText !== undefined ? this.props.finishButtonText:"Finish"}</Button>):null}

Props is not set properly. So custom class names are not set for finish button. Also the default css hides the button. This issue also appears in your demo page.

**Comment by EINazare** [comment]
Hello @cherma ,

Thank you for your interest in using this product.
Unfortunately i do not have time to work on it anymore.
If you want, you can open a pull request with the fixes for it.
I am going to make some changes when i will update [this product of ours](https://demos.creative-tim.com/now-ui-dashboard-pro-react/?_ga=2.86407771.233054020.1527576442-329288944.1519374311#/dashboard).
Until then, i will not be able to work on it.

Best,
Manu
