### ISSUE TITLE
last stepper width out of box

### ISSUE THREAD

**Issue by grinono** [creativetimofficial/react-bootstrap-wizard#6]
The last stepper in the sequence floats outside the wizard-container

<img width="1258" alt="schermafbeelding 2018-06-29 om 08 41 06" src="https://user-images.githubusercontent.com/4255206/42077154-38dbb06c-7b78-11e8-8ce7-975f953317dc.png">

**Comment by EINazare** [comment]
Hello @grinono ,

Thank you about this, if you have a fix, you can open a pull request.

Best,
Manu
